apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: argocd-managed-bucket-0
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
    uniformBucketLevelAccess: true
  providerConfigRef:
    name: default
